### ISSUE TITLE
Readme file has minimal.sh instructions.

### ISSUE THREAD

**Issue by KuJoe** [maxexcloo/Server#1]
Just a heads up. :)

**Comment by maxexcloo** [comment]
That's intentional...

**Comment by KuJoe** [comment]
Shouldn't the server.sh README have the instructions for server.sh?

**Comment by KuJoe** [comment]
Sorry, still getting used to GitHub, didn't mean to close the issue.

**Comment by maxexcloo** [comment]
The instructions are the same in both the script and the readme, I'm closing since it isn't an issue :)
